global using Sels.Core.Extensions;
global using Sels.Core.Extensions.Conversion;
global using Sels.Core.Extensions.Linq;
global using Sels.Core.Extensions.Logging;
global using Sels.Core.Extensions.Logging.Advanced;
global using Sels.Core.Extensions.Reflection;
global using Sels.Core.Data.SQL;
global using Sels.SQL.QueryBuilder.MySQL;
global using Sels.SQL.QueryBuilder.MySQL.MariaDb;