using System;
using System.Collections.Generic;
using System.Text;

namespace Sels.Core.Async.TaskManagement
{
    /// <summary>
    /// Exposes more options for named <see cref="IManagedTask"/>(s) scheduled using a <see cref="ITaskManager"/>.
    /// </summary>
    /// <typeparam name="TInput">The input for the task to create</typeparam>
    /// <typeparam name="TOutput">The output generated by the task</typeparam>
    public interface INamedManagedTaskCreationOptions<TInput, TOutput> : IManagedTaskCreationOptions<TInput, TOutput, INamedManagedTaskCreationOptions<TInput, TOutput>>
    {
        /// <summary>
        /// Defines the policy to use when dealing with named managed tasks.
        /// </summary>
        /// <param name="policy">The policy to use</param>
        /// <returns>Current options for method chaining</returns>
        INamedManagedTaskCreationOptions<TInput, TOutput> WithPolicy(NamedManagedTaskPolicy policy);
    }
}
